// src/components/Button.vue
<script setup lang="ts">
import Spinner from "./GSpinner.vue";
import Center from "./Center.vue";
import { useElementContext } from "~/composites/useElementContext";

const injectedElement = useElementContext();

const props = withDefaults(
  defineProps<{
    element?: string;
    look?: "solid" | "outline" | "ghost";
    isLoading?: boolean;
    disabled?: boolean;
  }>(),
  {
    element: undefined,
    look: "solid",
    isLoading: false,
    disabled: false,
  }
);

const _disabled = computed(() => props.isLoading || props.disabled);

const element = computed(() => props.element ?? injectedElement.value.normalizedName);

const buttonStyle = computed(() => {
  switch (props.look) {
    case "solid":
      return `bg-genshin-element-${element.value} transition-colors hover:bg-opacity-70 active:bg-opacity-50 text-black font-semibold shadow-md`;
    case "outline":
      return `border-1 border-genshin-element-${element.value} text-genshin-element-${element.value} bg-dark-900 transition-colors bg-opacity-0 hover:bg-opacity-20 active:bg-opacity-40`;
    case "ghost":
      return `text-genshin-element-${element.value} bg-dark-900 transition-colors bg-opacity-0 hover:bg-opacity-20 active:bg-opacity-40`;
  }
});
</script>

<template>
  <button
    type="button"
    :class="[buttonStyle, 'focus:outline-none focus-visible:ring h-[42px] px-4 rounded-lg ']"
    :disabled="_disabled"
    :aria-disabled="_disabled"
  >
    <Center>
      <Spinner v-if="isLoading" class="absolute" />
      <span :class="{ 'opacity-0': isLoading }">
        <slot />
      </span>
    </Center>
  </button>
</template>

// components/Button.tsx
import React from "react";
import { SemiCircle } from "./icons/semicircle";

interface ButtonProps {
    text: string;
    color?: string;
    onClick?: () => void;
    className?: string;
    secondary?: any;
    ternary?: any;
    link?: any;
    fullw?: any;
    isLoading?: any;
    disabled?: boolean | undefined;
}

function execIf(func: any, condition: boolean) {
    if (condition && func) func();
}

export const Button: React.FC<ButtonProps> = ({
    text,
    color,
    onClick,
    className,
    secondary,
    ternary,
    link,
    fullw,
    isLoading,
    disabled,
}) => {
    let cn: string = `buttoncommon shadow-md w-max text-gscale-dark-text-primary bg-opacity-70 bg-${color} ${className} transition-colors hover:bg-opacity-50 active:bg-opacity-30 hover:shadow-lg select-none focus-visible:ring focus:outline-none`;

    if (secondary) {
        cn = `buttoncommon ring-1 ring-opacity-80 text-${color} ring-${color} ${className} bg-black transition-colors bg-opacity-0 hover:bg-opacity-20 active:bg-opacity-50 focus:outline-none select-none focus-visible:bg-opacity-20`;
    } else if (ternary) {
        cn = `buttoncommon w-max text-${color} bg-black transition-colors bg-opacity-0 hover:bg-opacity-20 active:bg-opacity-50 select-none focus-visible:ring focus:outline-none ${className}`;
    } else if (link) {
        cn = `w-max text-${color} hover:underline select-none focus:outline-none focus-visible:underline ${className}`;
    }

    if (fullw) {
        cn += " !w-full";
    }

    if (disabled) {
        cn += /*tw*/ ` !bg-gray-700 opacity-40 cursor-default ring-0`;
    }

    return (
        <button
            className={cn + " flex justify-center relative"}
            disabled={disabled}
            onClick={() => execIf(onClick, !isLoading)}
        >
            <div className={isLoading ? "invisible" : ""}>{text}</div>
            {isLoading ? <SemiCircle className="absolute w-6 h-6 animate-spin" /> : null}
        </button>
    );
};
