// src/components/ItemCard.vue
<script setup lang="ts">
import { ItemWithAmount } from "~/lib/data/entities/ItemWithAmount";
import millify from "~/lib/millify";
import Image from "./Image.vue";

const props = defineProps<{ itemWithAmount: ItemWithAmount }>();
const _amountLabel = computed(() => millify(props.itemWithAmount.amount));
</script>

<template>
  <div class="rounded flex flex-col bg-dark-400 m-1 shadow w-max items-center overflow-hidden">
    <div class="h-12 p-1 w-12">
      <Image
        class="h-full object-contain w-full"
        type="material"
        :name="itemWithAmount.item.normalizedName"
        width="40"
        height="40"
        :alt="itemWithAmount.item.name"
      />
    </div>
    <div class="bg-dark-300 text-center w-full px-1">{{ _amountLabel }}</div>
  </div>
</template>

// components/ItemCard.tsx
import { Item } from "../data/items";
import { ItemImage } from "./ItemImage";

export default function ItemCard({ item, label }: { item: Item; label?: string }) {
    if (label && label === "0") return null;

    return (
        <div
            className={`flex flex-col items-center m-1 overflow-hidden rounded shadow bg-gscale-dark-background-primary`}
            style={{ height: "max-content" }}
        >
            <div className="w-12 h-12 p-1">
                <ItemImage item={item} />
            </div>
            {label ? (
                <div className="w-full px-1 text-center bg-gscale-dark-background-500">
                    {label}
                </div>
            ) : null}
        </div>
    );
}
