// src/pages/Index.vue
<script setup lang="ts">
import CharacterCard from "~/components/character/CharacterCard.vue";
import { charactersViewModel } from "~/lib/viewmodel/CharactersViewModel";
import Container from "~/components/PageContainer";
import SearchBar from "~/components/SearchBar.vue";
import type Fuse from "fuse.js";
import { ICharacterViewModel } from "~/lib/data/contracts/ICharacterViewModel";

//#region Search
const filteredCharacters = ref<Fuse.FuseResult<ICharacterViewModel>[] | null>(null);
const search = ref("");
let fuse: Fuse<ICharacterViewModel>;

throttledWatch(
  search,
  async (value) => {
    const Fuse = (await import("fuse.js")).default;
    if (fuse === undefined) {
      fuse = new Fuse(Object.values(charactersViewModel), {
        threshold: 0.2,
        useExtendedSearch: true,
        keys: [{ name: "name", weight: 3 }],
      });
    }

    filteredCharacters.value = fuse.search(value);
  },
  { throttle: 300 }
);
//#endregion

const characters = computed(() => {
  if (filteredCharacters.value && filteredCharacters.value.length > 0) {
    return filteredCharacters.value.map((res) => res.item);
  } else {
    return charactersViewModel;
  }
});
</script>

<template>
  <Container>
    <SearchBar v-model="search" placeholder="Search for Names, Materials, Elements, etc..." />
    <div w:grid="cols-2 sm:cols-3 lg:cols-4 xl:cols-5" w:gap="5 <sm:2" class="grid">
      <CharacterCard v-for="character in characters" :key="character.normalizedName" :character="character" />
    </div>
  </Container>
</template>

// pages/index.tsx
import {GetStaticProps} from "next";
import Layout from "../components/Layout";
import CharacterCard from "../components/CharacterCard";
import {characters as charactersList} from "../data/characters";
import {Search} from "../components/Search";
import {useEffect, useState} from "react";
import router from "next/router";
import {Character, Characters} from "../lib/MyTypes";

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            characters: charactersList,
        },
    };
};

const IndexPage = ({characters}: { characters: Characters }) => {
    const [search, setSearch] = useState<{ item: Character }[]>([]);
    const [searchTerm, setSearchTerm] = useState<string>("");

    return (
        <Layout title="Home" current="Characters">
            <div className="max-w-screen-xl mx-5 xl:mx-auto">
                <Search
                    onChange={async (e: any) => {
                        const {value} = e.currentTarget;
                        setSearchTerm(value)

                        const Fuse = (await import("fuse.js")).default;
                        const fuse = new Fuse(Object.values(characters), {
                            threshold: 0.2,
                            useExtendedSearch: true,
                            keys: [
                                {name: "name", weight: 3},
                                {name: "element", weight: 2},
                                {name: "weapon", weight: 2},
                                "rarity",
                                // "materials"
                                "materials.list.boss",
                                "materials.list.local",
                                "materials.list.weekly",
                                "materials.list.bookName",
                                "materials.list.commonName",
                            ],
                        });

                        //@ts-ignore
                        setSearch(fuse.search(value));
                    }}
                    onConfirm={() => {
                        if (search.length > 0) {
                            router.push(`/build/${search[0].item.id}`);
                        }

                        return false;
                    }}
                />
                <div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
                    {search.length === 0 ? (searchTerm.length > 0 ?
                        <div>No results</div> : Object.entries(characters).map(([_, character]) => {
                            return (
                                <CharacterCard
                                    character={character}
                                    key={character.id}
                                />
                            );
                        })) : search.map((character) => {
                        return (
                            <CharacterCard
                                character={character.item}
                                key={character.item.id}
                            />
                        );
                    })}
                </div>
            </div>
        </Layout>
    );
};

export default IndexPage;
